language: node_js
node_js:
    - "8"
    - "10"
    - "12"

before_script:

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - npm run cover
    - ./node_modules/.bin/codecov

sudo: false
