language: node_js
node_js:
    - "4"
    - "6"

before_script:
#   - npm install -g grunt-cli

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - npm run cover
    - ./node_modules/.bin/codecov

sudo: false
