#!/usr/bin/env node

'use strict';

let reporter

try {
    reporter = require('nodeunit').reporters.default
}
catch (e) {
    console.log(`Error: ${e.message}

Please run the following:

    npm install
`);
    process.exit()
}

process.chdir(__dirname)

let testDirs = [ 'test', 'test/readers'];

if (process.argv[2]) {
    testDirs = process.argv.slice(2);
    console.log(`Running tests: ${testDirs}`)
}

reporter.run(testDirs, undefined, (err) => {
    process.exit(((err) ? 1 : 0))
})